baseURL = 'https://robexley.github.io/renovation-project/'
languageCode = 'en-us'
title = 'Renovation Project'
copyright = "robexley"
theme = "ananke"

[params]
background_color_class = "bg-dark-green"